export default [
  {
    id: 'luar',
    name: 'Luar',
    main_color: '#0922AA',
    shoot_image: require('@assets/luar/shoot.png'),
    logo: require('@assets/luar/logo.svg'),
    client: 'Personal Project',
    role: 'UX/UI Designer',
    year: '2018',
    overview: 'The goal in this project is to ensure that users do not get saturated with many options when searching for a room or a roomie, and that by continuing to search their feed, they do not see the same thing again and again. What is proposed is to SAVE the options that you consider convenient and DISMISS with which you think you could not do MATCH.',
    slides: [
        require('@assets/luar/slide-1.jpg'),
        require('@assets/luar/slide-2.jpg'),
        require('@assets/luar/slide-3.jpg'),
        require('@assets/luar/slide-4.jpg'),
        require('@assets/luar/slide-5.jpg'),
        require('@assets/luar/slide-6.jpg'),
        require('@assets/luar/slide-7.jpg'),
        require('@assets/luar/slide-8.jpg'),
        require('@assets/luar/slide-9.jpg'),
        require('@assets/luar/slide-10.jpg'),
        require('@assets/luar/slide-11.jpg'),
        require('@assets/luar/slide-12.jpg'),
    ],
  },
  {
    id: 'checkout',
    name: 'Checkout',
    main_color: '#8CD9D2',
    shoot_image: require('@assets/checkout/shoot.png'),
    logo: require('@assets/checkout/logo.svg'),
    client: 'Personal Project',
    role: 'UX/UI Designer',
    year: '2019',
    overview: `◾️ Experimenting with more empty spaces and less colors, the more minimal posible, without sacrificing usability.`,
    slides: [
        require('@assets/checkout/slide-1.jpg'),
    ],
  },
  {
    id: 'onboarding',
    name: 'Onboarding',
    main_color: '#4232BC',
    shoot_image: require('@assets/onboarding/shoot.png'),
    logo: require('@assets/onboarding/logo.svg'),
    client: 'Personal Project',
    role: 'UX/UI Designer',
    year: '2019',
    overview: 'A sign up flow (only with phone number confirmation), along with a onboarding, a very intuitive path for a no social app.',
    slides: [
        require('@assets/onboarding/slide-1.jpg'),
    ],
  }
]
